const somClique=document.getElementById('somClique'),somSucesso=document.getElementById('somSucesso'),somErro=document.getElementById('somErro'),somVitoria=document.getElementById('somVitoria'),somAmbiente=document.getElementById('somAmbiente');
let deferredPrompt=null,ambient=false,fontSize=18,steps=JSON.parse(localStorage.getItem('bioSteps')||'[]');
function play(a){try{a.currentTime=0;a.play()}catch(e){}}
document.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>play(somClique)));
function openSection(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});localStorage.setItem('lastSection',id)}
function completeStep(n){if(!steps.includes(n))steps.push(n);localStorage.setItem('bioSteps',JSON.stringify(steps));updateProgress();play(somSucesso)}
function updateProgress(){const pct=Math.round((steps.length/12)*100);document.getElementById('progressBar').style.width=Math.min(pct,100)+'%';document.getElementById('progressText').textContent=`${Math.min(pct,100)}% concluído`}
function toggleAmbient(){ambient=!ambient;if(ambient){somAmbiente.volume=.3;somAmbiente.play()}else{somAmbiente.pause()}}
function fontUp(){fontSize+=2;document.documentElement.style.setProperty('--font',fontSize+'px')}
function fontDown(){fontSize=Math.max(16,fontSize-2);document.documentElement.style.setProperty('--font',fontSize+'px')}
function toggleDark(){document.body.classList.toggle('dark')}
function toggleContrast(){document.body.classList.toggle('contrast')}
function toggleDyslexic(){document.body.classList.toggle('dyslexic')}
function toggleAssistant(){document.getElementById('assistantPanel').classList.toggle('active')}
function copyText(id){const el=document.getElementById(id);el.select();document.execCommand('copy');play(somSucesso);alert('Texto copiado!')}
function selectGame(tipo){document.getElementById('promptBox').value=gamePrompts[tipo];document.getElementById('jogo').value=tipo;openSection('prompts');completeStep(6)}
const imageData=[['fundo-repro.png','Fundo geral do app','1920x1080','Crie um fundo digital educativo, acolhedor e científico sobre saúde reprodutiva, com elementos abstratos de células, DNA, anatomia simbólica, cores azul, lilás, ciano, branco e dourado suave, sem imagens explícitas.'],['robo-repro.png','Bio Guia','PNG transparente','Crie um mascote robô biólogo amigável, com jaleco, elementos de DNA e microscópio, estilo anime fofo, PNG com fundo transparente.'],['capa-repro.png','Tela inicial','1024x1024','Crie uma capa educativa sobre prevenção e autocuidado na saúde reprodutiva, com estudantes de Ciências Biológicas, ícones de saúde, DNA, microscópio e comunidade, estilo anime profissional.'],['memoria-repro.png','Jogo da memória','1024x1024','Crie imagem para jogo da memória sobre sistema reprodutor e prevenção, com cartas educativas, anatomia simbólica, ícones de autocuidado e estilo acolhedor.'],['quiz-repro.png','Quiz preventivo','1024x1024','Crie imagem de quiz educativo sobre saúde reprodutiva, com perguntas, alternativas grandes, ícones de ciência e prevenção, visual moderno e acessível.'],['cartas-repro.png','Cartas educativas','1024x1024','Crie imagem para jogo de cartas educativas sobre autocuidado, prevenção, exames e sistema reprodutor, sem exposição explícita, estilo anime científico.'],['cruzadas-repro.png','Palavras cruzadas','1024x1024','Crie imagem para palavras cruzadas de biologia sobre saúde reprodutiva, vocabulário científico, letras grandes e visual inclusivo.'],['mapa-repro.png','Mapa conceitual','1024x1024','Crie imagem de mapa conceitual interativo ligando sistema reprodutor, prevenção, autocuidado, IST, exames e educação em saúde.'],['trofeu-repro.png','Conclusão','1024x1024','Crie imagem de troféu de conclusão para oficina de extensão em Ciências Biológicas, com DNA, comunidade e prevenção em saúde.']];
function renderImages(){const box=document.getElementById('imageCards');box.innerHTML=imageData.map((i,idx)=>`<article class="card"><img src="assets/img/${i[0]}" alt="${i[1]}"><h3>${i[0]}</h3><p><strong>Função:</strong> ${i[1]}</p><p><strong>Tamanho:</strong> ${i[2]}</p><textarea id="imgPrompt${idx}" readonly>${i[3]}</textarea><button onclick="copyText('imgPrompt${idx}')">Copiar prompt</button></article>`).join('')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('btnInstall').style.display='inline-block'});
document.getElementById('btnInstall').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}else alert('No celular, use o menu do navegador e escolha Adicionar à tela inicial.')});
if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js')}
renderImages();updateProgress();openSection(localStorage.getItem('lastSection')||'inicio');
