const gamePrompts={
memoria:`Crie um jogo da memória educativo em HTML, CSS e JavaScript puro para estudantes de Ciências Biológicas desenvolverem ação de extensão sobre prevenção e autocuidado na saúde reprodutiva de mulheres e homens.
Público: comunidade em ação extensionista.
Tema: sistema reprodutor, prevenção, autocuidado, IST, exames preventivos, respeito, consentimento e educação em saúde.
Regras: 10 imagens/conceitos diferentes, cada um com par correspondente, total de 20 cartas. Cartas grandes, responsivas, sem tempo obrigatório, feedback positivo. Sons: clique.mp3, sucesso.mp3, erro.mp3, vitoria.mp3. Imagens em assets/img. Incluir tela inicial, instruções curtas, pontuação, botão reiniciar, alto contraste, A+/A-, modo escuro e mensagem final educativa. Não incluir imagens explícitas; usar ilustrações científicas, simbólicas e respeitosas. Entregue um único index.html completo.`,
quiz:`Crie um quiz educativo em HTML, CSS e JavaScript puro sobre prevenção e autocuidado na saúde reprodutiva, voltado para ação extensionista do curso de Ciências Biológicas. Faça 10 perguntas com 4 alternativas, linguagem clara, explicação após cada resposta, pontuação final, botão reiniciar e recursos de acessibilidade. Conteúdos: sistema reprodutor, IST, preservativos, vacinação, exames preventivos, sinais de alerta, autocuidado, consentimento e busca por serviços de saúde. Use assets/audio/clique.mp3, sucesso.mp3, erro.mp3, vitoria.mp3. Visual acolhedor, científico, sem exposição explícita. Entregue um único index.html completo.`,
cartas:`Crie um jogo de cartas educativas em HTML, CSS e JavaScript puro para Ciências Biológicas, sobre prevenção e autocuidado na saúde reprodutiva de mulheres e homens. Cada carta deve apresentar uma situação cotidiana, uma pergunta de reflexão, uma conduta preventiva e uma explicação biológica simples. Criar 12 cartas, botão próxima, revelar resposta, pontuação de participação, alto contraste, A+/A-, modo escuro, sons opcionais e mensagem final. Use imagens simbólicas em assets/img e sons em assets/audio. Entregue um único index.html completo.`,
cruzadas:`Crie um jogo de palavras cruzadas educativo em HTML, CSS e JavaScript puro sobre sistema reprodutor e prevenção em saúde reprodutiva para ação extensionista de Ciências Biológicas. Use 8 palavras: gametas, útero, próstata, testículo, ovário, preservativo, vacinação, prevenção. Dicas curtas, letras grandes, botão verificar, botão reiniciar, feedback positivo, acessibilidade 60+, sem tempo obrigatório e visual acolhedor. Entregue um único index.html completo.`,
mapa:`Crie um jogo de mapa conceitual interativo em HTML, CSS e JavaScript puro para relacionar estruturas do sistema reprodutor, funções biológicas e práticas de autocuidado. O aluno deve arrastar ou selecionar relações corretas entre cartões. Incluir 15 relações, feedback educativo, sons opcionais, layout responsivo, alto contraste, A+/A-, modo escuro e mensagem final. Tema: prevenção e autocuidado na saúde reprodutiva de mulheres e homens. Entregue um único index.html completo.`
};
