function val(id){return document.getElementById(id)?.value?.trim()||'Não informado.'}
function setIfEmpty(id,txt){const el=document.getElementById(id); if(el && !el.value.trim()) el.value=txt}
function bioGuiaRelatorio(){
setIfEmpty('introducao','A saúde reprodutiva constitui um campo essencial da educação em saúde, pois envolve conhecimentos biológicos, prevenção de agravos, autocuidado, respeito ao corpo, tomada de decisões informadas e acesso a serviços de saúde. No contexto da curricularização da extensão no curso de Ciências Biológicas, o desenvolvimento de jogos educativos digitais permite articular conteúdos científicos do sistema reprodutor com práticas de divulgação científica e intervenção educativa junto à comunidade. O projeto foi organizado em formato PWA, favorecendo acesso por celulares, tablets e computadores.');
setIfEmpty('justificativa','A atividade se justifica pela importância social de promover educação em saúde reprodutiva com linguagem clara, respeitosa e baseada em conhecimento científico. A curricularização da extensão possibilita que estudantes de Ciências Biológicas transformem conhecimentos acadêmicos sobre anatomia, fisiologia, prevenção e autocuidado em materiais digitais acessíveis para a comunidade. A proposta contribui para a prevenção de infecções sexualmente transmissíveis, valorização dos exames preventivos, compreensão do corpo humano, combate à desinformação e fortalecimento da autonomia em saúde.');
setIfEmpty('objetivo','Desenvolver um jogo educativo digital em formato PWA, voltado à promoção da prevenção e do autocuidado na saúde reprodutiva de mulheres e homens, articulando conteúdos do sistema reprodutor, educação em saúde, acessibilidade digital e curricularização da extensão no curso de Ciências Biológicas.');
setIfEmpty('objetivos','• Elaborar material educativo digital com linguagem científica simples e acessível.\n• Relacionar estruturas e funções do sistema reprodutor com práticas de prevenção e autocuidado.\n• Favorecer a aprendizagem por meio de jogos interativos.\n• Estimular a inclusão digital e a participação comunitária.\n• Publicar o aplicativo em formato PWA por meio do GitHub Pages.\n• Registrar o processo em relatório científico com evidências da produção.');
setIfEmpty('conteudo','Foram abordados conteúdos relacionados ao sistema reprodutor feminino e masculino, incluindo anatomia básica, gametogênese, ciclo menstrual, fecundação, contracepção, prevenção de IST, uso de preservativos, vacinação relacionada à prevenção, exames preventivos, sinais de alerta, autocuidado, consentimento, busca por serviços de saúde e divulgação científica responsável. O conteúdo foi organizado de modo educativo, sem exposição explícita, priorizando respeito, prevenção, linguagem acessível e adequação ao contexto extensionista.');
setIfEmpty('metodologiaDev','O desenvolvimento iniciou-se com a definição do tema e do tipo de jogo educativo. Em seguida, o grupo organizou a estrutura do projeto em pastas, definiu imagens, sons e ícones, criou prompts para geração do jogo com apoio de inteligência artificial e desenvolveu a aplicação utilizando HTML, CSS e JavaScript puro. O aplicativo foi planejado como PWA, com arquivo manifest.json, service worker, layout responsivo, recursos de acessibilidade, sons opcionais e publicação prevista via GitHub Pages.');
setIfEmpty('metodologiaAplicacao','A aplicação extensionista foi planejada para ocorrer em contexto educativo com mediação dos estudantes. Inicialmente, os participantes recebem explicação sobre o objetivo do jogo e orientações de uso. Em seguida, interagem com as atividades propostas, respondendo perguntas, associando conceitos ou explorando cartas educativas. Durante a aplicação, os estudantes observam clareza das instruções, facilidade de navegação, dúvidas frequentes, adequação da linguagem e percepção dos recursos visuais e sonoros. Ao final, podem ser coletadas impressões dos participantes para melhoria do material.');
setIfEmpty('recursosVisuais','Foram previstos fundo ilustrado, cards educativos, imagens simbólicas sobre sistema reprodutor, ícones de prevenção, personagem assistente Bio Guia, botões grandes, cores suaves, contraste adequado e organização visual responsiva. As imagens devem ser científicas, respeitosas, sem exposição explícita e adequadas ao ambiente universitário e comunitário.');
setIfEmpty('recursosSonoros','Os recursos sonoros incluem clique.mp3 para interação com botões, sucesso.mp3 para respostas corretas ou conclusão de etapas, erro.mp3 para necessidade de revisão, vitoria.mp3 para finalização do jogo e ambiente.mp3 como trilha opcional. Todos os sons devem ser curtos, suaves e permitir uso sem obrigatoriedade de áudio.');
setIfEmpty('acessRel','Foram incluídos recursos de acessibilidade como aumento e redução de fonte, alto contraste, modo escuro, fonte acessível, botões grandes, linguagem simples, instruções curtas, ausência de tempo obrigatório, textos alternativos nas imagens, feedback visual e sonoro opcional, navegação responsiva e integração com VLibras.');
setIfEmpty('resultados','Espera-se que o jogo contribua para a aprendizagem de conteúdos biológicos, ampliação da compreensão sobre prevenção e autocuidado, redução de dúvidas comuns, fortalecimento da divulgação científica e aproximação entre universidade e comunidade por meio de recurso digital acessível.');
setIfEmpty('discussao','A construção do PWA permitiu integrar conhecimentos de biologia, tecnologia, educação em saúde e extensão universitária. O uso de jogos digitais favorece a participação ativa e pode tornar temas sensíveis mais acessíveis quando tratados com respeito, linguagem clara e base científica. Também evidencia a importância da acessibilidade digital e da validação das informações utilizadas em materiais educativos.');
setIfEmpty('conclusao','A atividade demonstrou que estudantes de Ciências Biológicas podem atuar na produção de tecnologias educacionais voltadas à promoção da saúde. O desenvolvimento do jogo educativo em PWA possibilitou articular sistema reprodutor, prevenção, autocuidado, acessibilidade, inteligência artificial e extensão universitária, resultando em um recurso aplicável em ações de educação em saúde junto à comunidade.');
setIfEmpty('referencias','BRASIL. Ministério da Saúde. Protocolo Clínico e Diretrizes Terapêuticas para Atenção Integral às Pessoas com Infecções Sexualmente Transmissíveis.\nORGANIZAÇÃO MUNDIAL DA SAÚDE. Sexual and reproductive health and rights.\nOPAS/OMS. Autocuidado e saúde sexual e reprodutiva.\nW3C. Web Content Accessibility Guidelines (WCAG).\nMDN Web Docs. Progressive Web Apps.\nGitHub Docs. GitHub Pages.');
play(somSucesso);
}
function fileToBase64(file){return new Promise(res=>{const r=new FileReader();r.onload=e=>res(e.target.result);r.readAsDataURL(file)})}
async function gerarRelatorio(){const files=[...document.getElementById('prints').files];let imgs='';for(let i=0;i<files.length;i++){const b=await fileToBase64(files[i]);imgs+=`<div class="page-break"><h2>Evidência ${i+1}</h2><img src="${b}" alt="Print ou evidência enviada pelo grupo ${i+1}"></div>`}
document.getElementById('relatorioFinal').innerHTML=`<h1>Relatório Científico</h1><h2>Prevenção e Autocuidado na Saúde Reprodutiva</h2><p><strong>Grupo:</strong> ${val('grupo')}</p><p><strong>Integrantes:</strong> ${val('integrantes')}</p><p><strong>Curso:</strong> ${val('curso')}</p><p><strong>Jogo:</strong> ${val('jogo')}</p><h2>1. Introdução</h2><p>${val('introducao')}</p><h2>2. Justificativa Extensionista</h2><p>${val('justificativa')}</p><h2>3. Objetivo Geral</h2><p>${val('objetivo')}</p><h2>4. Objetivos Específicos</h2><p>${val('objetivos').replaceAll('\n','<br>')}</p><h2>5. Conteúdo Abordado</h2><p>${val('conteudo')}</p><h2>6. Metodologia de Desenvolvimento</h2><p>${val('metodologiaDev')}</p><h2>7. Metodologia de Aplicação</h2><p>${val('metodologiaAplicacao')}</p><h2>8. Recursos Visuais</h2><p>${val('recursosVisuais')}</p><h2>9. Recursos Sonoros</h2><p>${val('recursosSonoros')}</p><h2>10. Acessibilidade</h2><p>${val('acessRel')}</p><h2>11. Publicação no GitHub Pages</h2><p>${val('link')}</p><h2>12. Resultados Esperados</h2><p>${val('resultados')}</p><h2>13. Discussão</h2><p>${val('discussao')}</p><h2>14. Conclusão</h2><p>${val('conclusao')}</p><h2>15. Referências</h2><p>${val('referencias').replaceAll('\n','<br>')}</p>${imgs}`;play(somVitoria)}
async function gerarPDF(){await gerarRelatorio();html2pdf().set({margin:10,filename:'relatorio-saude-reprodutiva-ciencias-biologicas.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy']}}).from(document.getElementById('relatorioFinal')).save()}
function limparRelatorio(){document.querySelectorAll('#relatorio input,#relatorio textarea').forEach(e=>{if(e.type!=='file')e.value=''});document.getElementById('relatorioFinal').innerHTML='';play(somErro)}
